./run_kubernetes.sh

Error from server (AlreadyExists): pods "flaskdemo" already exists
NAME              READY   STATUS    RESTARTS   AGE
flaskdemo1         1/1    Running      1      14m27s

Forwarding from 127.0.0.1:8000 -> 80
Forwarding from [::1]:8000 -> 80
Handling connection for 8000
Handling connection for 8000
Handling connection for 8000


[2021-02-09 11:59:20,561] INFO in app: JSON payload:
{'CHAS': {'0': 0}, 'RM': {'0': 6.575}, 'TAX': {'0': 296.0}, 'PTRATIO': {'0': 15.3}, 'B': {'0': 396.9}, 'LSTAT': {'0': 4.98}}
[2021-02-09 11:59:20,597] INFO in app: Inference payload DataFrame:
   CHAS     RM    TAX  PTRATIO      B  LSTAT
0     0  6.575  296.0     15.3  396.9   4.98
[2021-02-09 11:59:20,619] INFO in app: Scaling Payload:
   CHAS     RM    TAX  PTRATIO      B  LSTAT
0     0  6.575  296.0     15.3  396.9   4.98
[2021-02-09 11:59:20,625] INFO in app: Prediction output:
[20.35373177134412]
127.0.0.1 - - [09/Feb/2021 11:59:20] "POST /predict HTTP/1.1" 200 -
